from . import account_invoice  # noqa
from . import account_payment_mode  # noqa
from . import delivery  # noqa
from . import magento_attribute_set  # noqa
from . import magento_backend  # noqa
from . import magento_binding  # noqa  # should be loaded first for inheritance
from . import magento_store  # noqa
from . import magento_storeview  # noqa
from . import magento_taxclass  # noqa
from . import magento_website  # noqa
from . import partner  # noqa
from . import partner_category  # noqa
from . import product  # noqa
from . import product_attribute  # noqa
from . import product_attribute_value  # noqa
from . import product_category  # noqa
from . import product_template  # noqa
from . import product_template_attribute_line  # noqa
from . import queue_job  # noqa
from . import sale_order  # noqa
from . import stock_picking  # noqa
